# Changes here will be overwritten by Copier
_commit: v1.0.0
_src_path: git@github.com:1zzzttt1/vue3-template.git
author_name: ymz
description: ai knowledge blog
project_name: logic
project_slug: logic
