import { describe, it, before } from 'node:test'
import assert from 'node:assert'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')

const knowledgeMetaPath = path.resolve(rootDir, 'src/data/knowledge-meta.ts')
const articlesMetaPath = path.resolve(rootDir, 'src/data/articles-meta.ts')

// Helper: extract JSON value from generated TS file
function extractJsonValue(content: string): unknown {
  // Match `const varName: Type = <json>` — greedy to capture full JSON
  const match = content.match(/=\s*(\{[\s\S]*\}|\[[\s\S]*\])\s*$/)
  if (!match) {
    throw new Error('Could not extract JSON value from generated file')
  }
  return JSON.parse(match[1]!)
}

describe('generate-metadata', () => {
  // Run the script first
  before(() => {
    // Clean up any previously generated files
    for (const p of [knowledgeMetaPath, articlesMetaPath]) {
      if (fs.existsSync(p)) {
        fs.unlinkSync(p)
      }
    }
  })

  it('should run generate-metadata.ts successfully', async () => {
    await import('./generate-metadata.ts')
    assert.ok(fs.existsSync(knowledgeMetaPath), 'knowledge-meta.ts should exist after running script')
    assert.ok(fs.existsSync(articlesMetaPath), 'articles-meta.ts should exist after running script')
  })

  it('should have auto-generated header comment', () => {
    const content = fs.readFileSync(knowledgeMetaPath, 'utf-8')
    assert.match(content, /Auto-generated by scripts\/generate-metadata\.ts/)
    assert.match(content, /DO NOT EDIT/)
  })

  describe('knowledge-meta.ts', () => {
    it('should contain the correct knowledge categories', () => {
      const content = fs.readFileSync(knowledgeMetaPath, 'utf-8')
      // Categories that exist as directories under src/data/knowledge/
      const categories = ['agent-skills', 'ai-development', 'build-with-claude-code', 'claude-code']
      for (const cat of categories) {
        assert.ok(content.includes(`"${cat}"`), `Should contain category: ${cat}`)
      }
    })

    it('should have correct export structure with types', () => {
      const content = fs.readFileSync(knowledgeMetaPath, 'utf-8')
      assert.match(content, /export const knowledgeMeta/)
      assert.match(content, /Record<string, KnowledgeArticleMeta\[\]>/)
      assert.match(content, /import type.*KnowledgeArticleMeta/)
    })

    it('should contain knowledge articles with correct fields', () => {
      const content = fs.readFileSync(knowledgeMetaPath, 'utf-8')
      const data = extractJsonValue(content) as Record<string, unknown[]>

      assert.ok(Object.keys(data).length > 0, 'Should have at least one category')

      for (const [cat, articles] of Object.entries(data)) {
        assert.ok(Array.isArray(articles), `${cat} should be an array`)
        assert.ok(articles.length > 0, `${cat} should have at least one article`)

        for (const article of articles) {
          const a = article as Record<string, unknown>
          assert.ok(typeof a.id === 'string', `${cat}: id should be string`)
          assert.ok(typeof a.title === 'string', `${cat}: title should be string`)
          assert.ok(typeof a.description === 'string', `${cat}: description should be string`)
          assert.ok(typeof a.category === 'string', `${cat}: category should be string`)
          assert.ok(typeof a.order === 'number', `${cat}: order should be number`)
        }
      }
    })

    it('should sort knowledge articles by order', () => {
      const content = fs.readFileSync(knowledgeMetaPath, 'utf-8')
      const data = extractJsonValue(content) as Record<string, unknown[]>

      for (const [cat, articles] of Object.entries(data)) {
        for (let i = 1; i < articles.length; i++) {
          const a = articles[i] as Record<string, unknown>
          const b = articles[i - 1] as Record<string, unknown>
          assert.ok(
            a.order >= b.order,
            `${cat}: articles not sorted by order at index ${i}`
          )
        }
      }
    })
  })

  describe('articles-meta.ts', () => {
    it('should have correct export structure with types', () => {
      const content = fs.readFileSync(articlesMetaPath, 'utf-8')
      assert.match(content, /export const articlesMeta/)
      assert.match(content, /ArticleMeta\[\]/)
      assert.match(content, /import type.*ArticleMeta/)
    })

    it('should contain articles with correct fields', () => {
      const content = fs.readFileSync(articlesMetaPath, 'utf-8')
      const data = extractJsonValue(content) as unknown[]

      assert.ok(data.length > 0, 'Should have at least one article')

      for (const article of data) {
        const a = article as Record<string, unknown>
        assert.ok(typeof a.id === 'string', 'id should be string')
        assert.ok(typeof a.title === 'string', 'title should be string')
        assert.ok(typeof a.summary === 'string', 'summary should be string')
        assert.ok(Array.isArray(a.tags), 'tags should be array')

        // publishedAt should be present, even if empty string
        assert.ok(typeof a.publishedAt === 'string', 'publishedAt should be string')
      }
    })

    it('should sort articles by publishedAt descending', () => {
      const content = fs.readFileSync(articlesMetaPath, 'utf-8')
      const data = extractJsonValue(content) as Record<string, unknown>[]

      if (data.length > 1) {
        for (let i = 1; i < data.length; i++) {
          const a = data[i] as Record<string, unknown>
          const b = data[i - 1] as Record<string, unknown>
          if (a.publishedAt && b.publishedAt) {
            assert.ok(
              a.publishedAt <= b.publishedAt,
              'articles not sorted by publishedAt descending'
            )
          }
        }
      }
    })
  })
})
