import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseFrontmatter } from '../src/utils/frontmatter'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')

const HEADER = '// Auto-generated by scripts/generate-metadata.ts. DO NOT EDIT.\n'

// ---- Types ----

interface KnowledgeArticleMeta {
  id: string
  title: string
  description: string
  category: string
  order: number
}

interface ArticleMeta {
  id: string
  title: string
  summary: string
  tags: string[]
  publishedAt: string
  sourceUrl: string
  sourceTitle: string
  sourceAuthor?: string
  createdAt: string
  updatedAt: string
}

// ---- Knowledge Metadata ----

function generateKnowledgeMeta(): Record<string, KnowledgeArticleMeta[]> {
  const knowledgeDir = path.resolve(rootDir, 'src/data/knowledge')

  if (!fs.existsSync(knowledgeDir)) {
    console.warn(`Warning: knowledge directory not found: ${knowledgeDir}`)
    return {}
  }

  const entries = fs.readdirSync(knowledgeDir, { withFileTypes: true })
  const categories = entries
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name)
    .sort()

  const knowledgeMeta: Record<string, KnowledgeArticleMeta[]> = {}

  for (const category of categories) {
    const categoryPath = path.join(knowledgeDir, category)
    const files = fs
      .readdirSync(categoryPath)
      .filter((f) => f.endsWith('.md'))
      .sort()

    const articles: KnowledgeArticleMeta[] = files.map((file) => {
      const content = fs.readFileSync(path.join(categoryPath, file), 'utf-8')
      const { metadata } = parseFrontmatter(content)
      const id = file.replace(/\.md$/, '')
      return {
        id,
        title: (metadata.title as string) || id,
        description: (metadata.description as string) || '',
        category,
        order: Number(metadata.order) || 0,
      }
    })

    articles.sort((a, b) => a.order - b.order)
    knowledgeMeta[category] = articles
  }

  const output = `${HEADER}
import type { KnowledgeArticleMeta } from '@/types'

export const knowledgeMeta: Record<string, KnowledgeArticleMeta[]> = ${JSON.stringify(knowledgeMeta, null, 2)}
`

  const outPath = path.resolve(rootDir, 'src/data/knowledge-meta.ts')
  fs.writeFileSync(outPath, output, 'utf-8')
  console.log(`Generated: ${path.relative(rootDir, outPath)}`)

  return knowledgeMeta
}

// ---- Articles Metadata ----

function generateArticlesMeta(): ArticleMeta[] {
  const articlesDir = path.resolve(rootDir, 'src/data/articles')

  if (!fs.existsSync(articlesDir)) {
    console.warn(`Warning: articles directory not found: ${articlesDir}`)
    return []
  }

  const files = fs
    .readdirSync(articlesDir)
    .filter((f) => f.endsWith('.md'))
    .sort()

  const articlesMeta: ArticleMeta[] = files.map((file) => {
    const content = fs.readFileSync(path.join(articlesDir, file), 'utf-8')
    const { metadata } = parseFrontmatter(content)
    const id = file.replace(/\.md$/, '')
    return {
      id,
      title: (metadata.title as string) || id,
      summary: (metadata.summary as string) || '',
      tags: (metadata.tags as string[]) || [],
      publishedAt: (metadata.publishedAt as string) || '',
      sourceUrl: (metadata.sourceUrl as string) || '',
      sourceTitle: (metadata.sourceTitle as string) || '',
      sourceAuthor: (metadata.sourceAuthor as string) || undefined,
      createdAt: (metadata.createdAt as string) || (metadata.publishedAt as string) || '',
      updatedAt: (metadata.updatedAt as string) || (metadata.publishedAt as string) || '',
    }
  })

  articlesMeta.sort((a, b) => {
    if (!a.publishedAt && !b.publishedAt) return 0
    if (!a.publishedAt) return 1
    if (!b.publishedAt) return -1
    return b.publishedAt.localeCompare(a.publishedAt)
  })

  const output = `${HEADER}
import type { ArticleMeta } from '@/types'

export const articlesMeta: ArticleMeta[] = ${JSON.stringify(articlesMeta, null, 2)}
`

  const outPath = path.resolve(rootDir, 'src/data/articles-meta.ts')
  fs.writeFileSync(outPath, output, 'utf-8')
  console.log(`Generated: ${path.relative(rootDir, outPath)}`)

  return articlesMeta
}

// ---- Entry Point ----

export function generateMetadata(): void {
  generateKnowledgeMeta()
  generateArticlesMeta()
}

generateMetadata()
