// Auto-generated by scripts/generate-metadata.ts. DO NOT EDIT.

import type { ArticleMeta } from '@/types'

export const articlesMeta: ArticleMeta[] = [
  {
    "id": "hello",
    "title": "AI Agent 的外部能力： \"MCP\" 还是 \"SKill + CLI\"？",
    "summary": "",
    "tags": [
      "CLI",
      "MCP"
    ],
    "publishedAt": "2026-04-05",
    "sourceUrl": "",
    "sourceTitle": "",
    "createdAt": "2026-04-05",
    "updatedAt": "2026-04-05"
  }
]
