// Auto-generated by scripts/generate-metadata.ts. DO NOT EDIT.

import type { ArticleMeta } from '@/types'

export const articlesMeta: ArticleMeta[] = [
  {
    "id": "Superpowers",
    "title": "Superpowers： 强大的 TDD（测试驱动开发）",
    "summary": "",
    "tags": [
      "AI Coding",
      "测试驱动开发"
    ],
    "publishedAt": "2026-04-20",
    "sourceUrl": "",
    "sourceTitle": "",
    "createdAt": "2026-04-20",
    "updatedAt": "2026-04-20"
  },
  {
    "id": "OpenSpec",
    "title": "OpenSpec：灵活的 SDD（规范驱动开发）",
    "summary": "",
    "tags": [
      "AI Coding",
      "规范驱动开发"
    ],
    "publishedAt": "2026-04-15",
    "sourceUrl": "",
    "sourceTitle": "",
    "createdAt": "2026-04-15",
    "updatedAt": "2026-04-15"
  },
  {
    "id": "hello",
    "title": "AI Agent 的外部能力： \"MCP\" 还是 \"SKill + CLI\"？",
    "summary": "",
    "tags": [
      "CLI",
      "MCP"
    ],
    "publishedAt": "2026-04-05",
    "sourceUrl": "",
    "sourceTitle": "",
    "createdAt": "2026-04-05",
    "updatedAt": "2026-04-05"
  },
  {
    "id": "claude-code-best-practices",
    "title": "Claude Code 最佳实践：如何高效使用 AI 编程助手",
    "summary": "深入探讨 Claude Code 的核心使用策略，包括提示词技巧、工作流程优化和实际应用场景。",
    "tags": [
      "AI",
      "Claude Code",
      "效率工具"
    ],
    "publishedAt": "2025-01-15",
    "sourceUrl": "https://example.com/claude-code-guide",
    "sourceTitle": "Claude Code 官方文档",
    "sourceAuthor": "Anthropic",
    "createdAt": "2025-01-15",
    "updatedAt": "2025-01-15"
  },
  {
    "id": "token-cost-analysis",
    "title": "大语言模型 Token 成本分析：如何优化你的 API 支出",
    "summary": "详细分析 Token 计算方式对 API 成本的影响，提供实用的成本优化策略。",
    "tags": [
      "AI",
      "成本优化",
      "LLM"
    ],
    "publishedAt": "2025-01-10",
    "sourceUrl": "https://example.com/token-cost-guide",
    "sourceTitle": "LLM API 成本优化指南",
    "createdAt": "2025-01-10",
    "updatedAt": "2025-01-10"
  },
  {
    "id": "ai-agent-workflow",
    "title": "AI Agent 工作流设计：从理论到实践",
    "summary": "探索 AI Agent 的设计模式和最佳实践，构建可靠的自动化工作流程。",
    "tags": [
      "AI",
      "Agent",
      "工作流"
    ],
    "publishedAt": "2025-01-05",
    "sourceUrl": "https://example.com/ai-agent-design",
    "sourceTitle": "AI Agent 设计模式",
    "createdAt": "2025-01-05",
    "updatedAt": "2025-01-05"
  }
]
