// Auto-generated by scripts/generate-metadata.ts. DO NOT EDIT.

import type { KnowledgeArticleMeta } from '@/types'

export const knowledgeMeta: Record<string, KnowledgeArticleMeta[]> = {
  "agent-skills": [
    {
      "id": "Skills是什么",
      "title": "1. Skills 是什么？",
      "description": "阅读时间：20分钟",
      "category": "agent-skills",
      "order": 1
    },
    {
      "id": "规范说明",
      "title": "2. 规范说明",
      "description": "阅读时间：30分钟",
      "category": "agent-skills",
      "order": 2
    },
    {
      "id": "快速创建Skill",
      "title": "3. 快速创建 Skill",
      "description": "阅读时间：10分钟",
      "category": "agent-skills",
      "order": 3
    },
    {
      "id": "Skill 创建者的最佳实践",
      "title": "4. Skill 创建者的最佳实践",
      "description": "阅读时间：30分钟",
      "category": "agent-skills",
      "order": 4
    },
    {
      "id": "优化 skill 描述",
      "title": "5. 优化 Skill 描述",
      "description": "阅读时间：10分钟",
      "category": "agent-skills",
      "order": 5
    },
    {
      "id": "评估技能产出质量",
      "title": "6. 评估 skill 产出质量",
      "description": "阅读时间：10分钟",
      "category": "agent-skills",
      "order": 6
    },
    {
      "id": "如何在 Skill 里使用脚本",
      "title": "7. 在 Skill 中使用 script",
      "description": "阅读时间：10分钟",
      "category": "agent-skills",
      "order": 7
    }
  ],
  "ai-development": [
    {
      "id": "getting-started",
      "title": "AI 应用开发实战",
      "description": "从零开始开发 AI 应用的完整指南",
      "category": "ai-development",
      "order": 1
    }
  ],
  "build-with-claude-code": [
    {
      "id": "用skills扩展claudecode",
      "title": "skills扩展 Claude code",
      "description": "阅读时间：30分钟",
      "category": "build-with-claude-code",
      "order": 1
    }
  ],
  "claude-code": [
    {
      "id": "claudecode如何工作",
      "title": "Claude Code 如何工作",
      "description": "阅读时间：30分钟",
      "category": "claude-code",
      "order": 1
    }
  ]
}
